name: quranai_flutter_app
description: تطبيق الكوثر - تطبيق ذكي لتحليل وتحسين تلاوة القرآن الكريم.

publish_to: 'none' # لعدم نشر التطبيق على pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # واجهة المستخدم
  cupertino_icons: ^1.0.5
  
  # إدارة الحالة
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  
  # تسجيل الصوت
  flutter_sound: ^9.2.13
  permission_handler: ^10.2.0
  
  # طلبات الشبكة
  http: ^1.1.0
  http_parser: ^4.0.2
  
  # التخزين المحلي
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  
  # المساعدة
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/
  
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
    
    - family: Uthmanic
      fonts:
        - asset: assets/fonts/UthmanicHafs.ttf
